from flask_marshmallow import Marshmallow
from marshmallow_sqlalchemy import SQLAlchemySchema,auto_field
from models import Book

ma = Marshmallow()
class BookSchema(ma.SQLAlchemySchema):
    class Meta:
        model = Book
        load_instance = True

    # id = ma.auto_field()
    # title = ma.auto_field()
    # author = ma.auto_field()
    id = auto_field(dump_only=True)  # Typically 'id' is generated by DB, so dump_only for POST/PUT
    title = auto_field()
    author = auto_field()
    genre = auto_field()
    year = auto_field()

book_schema = BookSchema()
books_schema = BookSchema(many=True)